from typing import Any, Dict, List, Optional


def build_router_plan(
    *,
    task_type: str,
    reason: str,
    steps: List[str],
    needs_more_context: bool,
    missing_context: List[str],
    follow_up_question: Optional[str],
    domain: Optional[str] = None,
    action: Optional[str] = None,
    goal: Optional[str] = None,
    subgoals: Optional[List[str]] = None,
    resources: Optional[List[str]] = None,
    required_context: Optional[List[str]] = None,
    confidence: Optional[float] = None,
    plan_type: Optional[str] = None,
    evidence_policy: Optional[str] = None,
    stop_criteria: Optional[List[str]] = None,
) -> Dict[str, Any]:
    return {
        "task_type": task_type,
        "reason": reason,
        "steps": steps,
        "needs_more_context": needs_more_context,
        "missing_context": missing_context,
        "follow_up_question": follow_up_question,
        "planner_source": "router",
        "domain": domain,
        "action": action,
        "goal": goal,
        "subgoals": subgoals or [],
        "resources": resources or [],
        "required_context": required_context or [],
        "confidence": confidence,
        "plan_type": plan_type,
        "evidence_policy": evidence_policy,
        "stop_criteria": stop_criteria or [],
    }
